In [2]:
import numpy as np

In [ ]:
def conv2D(matrix:np.array,kernel:np.array):
    # get the dimensions of the matrix and kernel:
    m_rows, m_cols = matrix.shape
    k_rows, k_cols = kernel.shape
    
    # no padding, so the output dimensions will be:
    out_rows = m_rows - k_rows + 1 + 2
    out_cols = m_cols - k_cols + 1 + 2
    
    # initialize the output matrix:
    output = np.zeros((out_rows, out_cols))
    
    for i in range(out_rows):
        for j in range(out_cols):
            # extract the region of interest:
            region = matrix[i:i+k_rows, j:j+k_cols]
            # perform element-wise multiplication and sum:
            output[i, j] = np.clip(np.round(np.sum(region * kernel)), 0, 255)
    
    return output

In [20]:
original_matrix = np.array([
    [0, 10, 1, 8, 1, 8, 8, 1],
    [8, 0, 8, 1, 28, 0, 10, 1],
    [29, 10, 29, 28, 28, 29, 28, 1],
    [3, 10, 3, 1, 5, 0, 3, 6],
    [28, 0, 28, 29, 1, 1, 10, 15],
    [28, 1, 29, 10, 10, 1, 10, 1],
    [29, 28, 28, 0, 12, 29, 3, 21],
    [29, 30, 3, 1, 5, 0, 1, 6]
])

# box filter

In [21]:
kernel_box = np.array([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])

In [22]:
# citra hasil menggunakan kernel box:
result_box = conv2D(original_matrix, kernel_box)
print("Hasil konvolusi dengan kernel box: (dibulatkan ke bilangan bulat terdekat)")
print(result_box)

Hasil konvolusi dengan kernel box: (dibulatkan ke bilangan bulat terdekat)
[[10.55555556 10.55555556 14.66666667 14.55555556 15.55555556  9.55555556]
 [11.11111111 10.         14.55555556 13.33333333 14.55555556  8.66666667]
 [15.55555556 15.33333333 16.88888889 13.55555556 11.66666667 10.33333333]
 [14.44444444 12.33333333 12.88888889  6.44444444  4.55555556  5.22222222]
 [22.11111111 17.         16.33333333 10.33333333  8.55555556 10.11111111]
 [22.77777778 14.44444444 10.88888889  7.55555556  7.88888889  8.        ]]


# Weighted average Filter

In [23]:
weighted_kernel = np.array([
    [1/16, 2/16, 1/16],
    [2/16, 4/16, 2/16],
    [1/16, 2/16, 1/16]
])

In [24]:
# citra hasil menggunakan kernel weighted:
result_weighted = conv2D(original_matrix, weighted_kernel)
print("\nHasil konvolusi dengan kernel weighted: (dibulatkan ke bilangan bulat terdekat)")
print(result_weighted)


Hasil konvolusi dengan kernel weighted: (dibulatkan ke bilangan bulat terdekat)
[[ 8.1875  9.375  12.9375 15.3125 13.4375  9.5625]
 [12.375  14.125  17.125  18.375  17.125  12.8125]
 [11.625  13.4375 13.75   10.4375  8.9375  9.125 ]
 [12.3125 16.     15.1875  6.625   3.5     6.625 ]
 [17.9375 19.1875 15.3125  9.1875  8.125   8.5   ]
 [23.5625 17.125   9.3125  9.25   10.875   8.875 ]]


# Mask/Filter konvolusi

In [26]:
mask_kernel = np.array([
    [1, 1, 1],
    [1, 3, 1],
    [1, 1, 1]
])

In [27]:
result_mask = conv2D(original_matrix, mask_kernel)
print("\nHasil konvolusi dengan kernel mask: (dibulatkan ke bilangan bulat terdekat)")
print(result_mask)


Hasil konvolusi dengan kernel mask: (dibulatkan ke bilangan bulat terdekat)
[[ 95. 111. 134. 187. 140. 106.]
 [120. 148. 187. 176. 189. 134.]
 [160. 144. 154. 132. 105.  99.]
 [130. 167. 174.  60.  43.  67.]
 [201. 211. 167. 113.  79. 111.]
 [255. 186.  98.  92. 129.  78.]]


# Citra menggunakan Max,min, median Filter (3x3)

In [38]:
def filter(matrix:np.array,filter_type:str):
    M,N = matrix.shape
    
    window = np.zeros(9)
    image_result = np.zeros((M-2,N-2))
    
    for i in range(1,M-1):
        for j in range(1,N-1):
            window[0] = matrix[i-1][j-1]
            window[1] = matrix[i-1][j]
            window[2] = matrix[i-1][j+1]
            window[3] = matrix[i][j-1]
            window[4] = matrix[i][j]
            window[5] = matrix[i][j+1]
            window[6] = matrix[i+1][j-1]
            window[7] = matrix[i+1][j]
            window[8] = matrix[i+1][j+1]
            
            if filter_type == "median":
                image_result[i-1][j-1] = np.median(window)
            elif filter_type == "max":
                image_result[i-1][j-1] = np.max(window)
            elif filter_type == "min":
                image_result[i-1][j-1] = np.min(window)

    return image_result
    

In [39]:
max_result = filter(original_matrix, "max")
print("\nHasil filter max:")
print(max_result)


Hasil filter max:
[[29. 29. 29. 29. 29. 29.]
 [29. 29. 29. 29. 29. 29.]
 [29. 29. 29. 29. 29. 29.]
 [29. 29. 29. 29. 10. 15.]
 [29. 29. 29. 29. 29. 29.]
 [30. 30. 29. 29. 29. 29.]]


In [40]:
median_result = filter(original_matrix, "median")
print("\nHasil filter median:")
print(median_result)


Hasil filter median:
[[ 8.  8.  8.  8. 10.  8.]
 [ 8.  8.  8.  5. 10.  3.]
 [10. 10. 28.  5.  5.  6.]
 [10. 10. 10.  1.  3.  3.]
 [28. 28. 12. 10. 10. 10.]
 [28. 10. 10.  5.  5.  3.]]


In [41]:
min_result = filter(original_matrix, "min")
print("\nHasil filter min:")
print(min_result)


Hasil filter min:
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0. 0.]]
